### ISSUE TITLE
ImportError: No module named Crypto.Cipher

### ISSUE THREAD

**Issue by bitmessagemac** [prof7bit/goxtool#37]
Does this work on mac's? Would you be able to provide a little guidance of how to download this dependency please? (I'm a programmer, just not familiar with python.)

```
± ./goxtool.py
Traceback (most recent call last):
  File "./goxtool.py", line 30, in <module>
    import goxapi
  File "/Users/F/Documents/Business/Prospects/BTC trading/tools/goxtool (python)/git-goxtool/goxtool/goxapi.py", line 34, in <module>
    from Crypto.Cipher import AES
ImportError: No module named Crypto.Cipher
```

**Comment by yaoelcn** [comment]
error: Microsoft Visual C++ 9.0 is required (Unable to find vcvarsall.bat). Get it from http://aka.ms/vcpython27

try to download.
I try, and I figure out this problem

**Comment by prof7bit** [comment]
It won't work natively on windows, you will need to run it with cygwin.

But why are you trying to nun it anyway? MtGox no longer exists, so there is absolutely no use for it at all.

**Comment by Delerium69** [comment]
it will always exist in my heart :(

**Comment by nii236** [comment]
Mine too!

**Comment by acriptis** [comment]
Never forget goxtool! It inspires me to continue development of btc-e analogue software

**Comment by nii236** [comment]
I'm surprised people haven't repurposed Goxtool to connect to other exchanges yet

**Comment by acriptis** [comment]
@nii236 after your message I decided to start porting the goxtool into a bitfinextool.
Now it can observe the bitfinex market with websockets and http:
![bitfinextool](https://cloud.githubusercontent.com/assets/2207706/11384852/939f61a4-9324-11e5-8c1c-87de659a8e49.png)

**Comment by nii236** [comment]
@acriptis Please share your work! :+1:

**Comment by acriptis** [comment]
@nii236 okay, I gonna finish porting functionality of order-making and share it with people.

**Comment by Delerium69** [comment]
Cool - excellent work

**Comment by acriptis** [comment]
@nii236, @prof7bit and who may concern
here is my port of goxtool for bitfinex.com market: https://github.com/acriptis/bfxtool
Test and review please.

**Comment by nii236** [comment]
Awesome! Will check it out!

**Comment by Delerium69** [comment]
great stuff acriptis - ill take a look

**Comment by ravibhojwani** [comment]
As a creditor of Mtgox - something tells me I’m not cursed but my Coins will be back.

**Comment by nii236** [comment]
I've created a [candlestick library](https://github.com/nii236/candlestick) (port of an existing Python one) that will form the base of my goxtool replacement.
